### ISSUE TITLE
проверка выполняется только при использовании этого конструктора, но если через пустой конструктор+ сеттеры не выполнится, так?

### ISSUE THREAD

**Issue by tgurskaya96** [antoluk/JavaWorkshop#2]
https://github.com/antoluk/JavaWorkshop/blob/cad1e8b61f668d230b795b22fa53333f0363d322/src/main/java/com/example/demo/logic/SinIntegral.java#L14

**Comment by antoluk** [comment]
Да, это так. Проверка была перенесена в метод parseInput, теперь исключение отлавливается до создания классов. по поводу сеттеров класс не хранит ввод пользователя, следовательно и сеттера для значений right и left нету.
